# Generated by Django 5.1.7 on 2025-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_serial', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('objects_data', models.JSONField()),
                ('snapshot_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
