# Generated by Django 5.1.7 on 2025-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco_be_launch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
