# Generated by Django 5.2 on 2025-04-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco_be_launch', '0003_camera_customcvevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomCVEvent',
            new_name='Event',
        ),
        migrations.DeleteModel(
            name='DetectionEvent',
        ),
    ]
