# Generated by Django 5.2 on 2025-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco_be_launch', '0004_rename_customcvevent_event_delete_detectionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('reward', models.IntegerField(default=0)),
            ],
        ),
    ]
